// Central features index exporting all pages and screens
export { default as Home, default as HomePage } from './home/HomePage'
export { default as ProductMap, default as ProductMapPage } from './product/ProductMapPage'
export { default as ProductApp, default as ProductAppPage } from './product/ProductAppPage'
export { default as Login, default as LoginPage } from './auth/LoginPage'
export { default as Signup, default as SignupPage } from './auth/SignupPage'
export { default as Docs, default as DocsPage } from './docs/DocsPage'
export { default as SurveyStudioPage } from './survey/SurveyStudioPage'
export { default as SurveyHistoryPage } from './survey/SurveyHistoryPage'
export { default as ReviewerWorkspacePage } from './review/ReviewerWorkspacePage'
export { ReviewerHubPage } from './review/ReviewerHubPage'
export { CandidateReviewPage } from './review/CandidateReviewPage'
export { RevalidationReviewPage } from './review/RevalidationReviewPage'
export { default as WalletPage } from './wallet/WalletPage'
export { default as CatalogPage } from './catalog/CatalogPage'
export { default as TermsPage } from './legal/TermsPage'
export { default as PrivacyPage } from './legal/PrivacyPage'
export { default as ProfilePage } from './profile/ProfilePage'
